### ISSUE TITLE
No triplane file when running optimization

### ISSUE THREAD

**Issue by gongmm** [jiaxinxie97/HFGI3D#1]
when running python run_pti.py ../../example_configs/config_00001.py this appear
Traceback (most recent call last):
  File "HFGI3D/inversion/scripts/../../multi_views/generate_multi_views.py", line 464, in <module>
    triplane_image = imageio.imread(triplane_file) / 255.
  File "miniconda3/envs/hfgi3d/lib/python3.9/site-packages/imageio/v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "miniconda3/envs/hfgi3d/lib/python3.9/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "miniconda3/envs/hfgi3d/lib/python3.9/site-packages/imageio/core/request.py", line 248, in __init__
    self._parse_uri(uri)
  File "miniconda3/envs/hfgi3d/lib/python3.9/site-packages/imageio/core/request.py", line 408, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'HFGI3D/inversion/output/00001/230_output/0.png' 
folder 230_output is empty

**Comment by jiaxinxie97** [comment]
Hi,

Can you track the previous error of the running, if the 230_output is empty, there is something wrong in running [ ](https://github.com/jiaxinxie97/HFGI3D/blob/fcc863598dedb221cad67f757b242c798d61abab/inversion/scripts/run_pti.py#L58)
